# Generated by Django 3.2 on 2022-10-01 10:41

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_usercurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Right',
                'verbose_name_plural': 'Rights',
            },
        ),
        migrations.CreateModel(
            name='GroupRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.fields.related.OneToOneField, to='auth.group')),
                ('rights', models.ManyToManyField(related_name='rigths', to='main.Right')),
            ],
            options={
                'verbose_name': 'Rigths - Group',
                'verbose_name_plural': 'Rigths - Groups',
            },
        ),
    ]
