# Generated by Django 3.2 on 2022-10-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_groupright_right'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercurso',
            old_name='ulr_certificado',
            new_name='url_certificado',
        ),
    ]
